Repository redhat-plumbers-in-action/storypointer, pull requests merged in 2024-08, with the labels that each got.

#5 Add README
  .github/workflows/tests.yml
  README.md
Labels: type: documentation

#6 feat: add support to filter by assignee
  src/jira.ts
  src/main.ts
Labels: type: feature

#7 doc: add API key documentation
  README.md
Labels: type: documentation

#10 doc: add note about fetch limitation
  README.md
Labels: type: documentation

#14 ci: fix publish workflow
  .github/workflows/publish.yml
Labels: type: ci

#15 feat: add support for skipping issues
  package.json
  src/main.ts
  src/schema/jira.ts
Labels: type: feature

#21 Update description
  README.md
Labels: type: documentation

#22 feat: add option to store configuration in `.config` directory
  .gitignore
  README.md
  src/main.ts
  src/util.ts
Labels: type: feature

#23 rpm: package storypointer to Fedora
  .npmignore
  .packit.yaml
  rpm/nodejs-storypointer.spec
  rpm/storypointer-bundled-licenses.txt
Labels: type: feature

#24 packit: build dist files when building from PR
  .npmignore
  .packit.yaml
  LICENSE-BUNDLED
  rpm/nodejs-storypointer.spec
Labels: type: maintenance

#31 Add new option to show legend for beter understanding of the output
  README.md
  src/legend.ts
  src/main.ts
Labels: type: feature

#32 Allow to configure default values for `assignee`, `component` and `developer`
  README.md
  src/main.ts
  src/util.ts
Labels: type: feature

#34 feat: use user login as default assignee
  README.md
  src/main.ts
  src/util.ts
Labels: type: feature

#37 feat: show used JQL in the log
  README.md
  src/jira.ts
  src/main.ts
Labels: type: feature

#38 fix: load configuration by absolute path
  src/main.ts
Labels: type: bugfix

#39 feat: allow to disable default values
  README.md
  src/util.ts
Labels: type: feature

#40 fix: remove debug logging used during development
  src/util.ts
Labels: type: bugfix
